In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("/content/housing.csv")
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [5]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [9]:
df['price'].max()

7700000

In [21]:
#How many houses are having grade 10?
df.groupby('grade').size()

grade
1        1
3        3
4       29
5      242
6     2038
7     8981
8     6068
9     2615
10    1134
11     399
12      90
13      13
dtype: int64

In [16]:
#OR
df[(df['grade']==10)]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
66,3394100030,20140909T000000,975000,4,2.50,2720,11049,2.0,0,0,...,10,2720,0,1989,0,98004,47.5815,-122.192,2750,11049
75,3276920270,20141105T000000,832500,4,4.00,3430,35102,2.0,0,0,...,10,2390,1040,1986,0,98075,47.5822,-121.987,3240,35020
79,1531000030,20150323T000000,720000,4,2.50,3450,39683,2.0,0,0,...,10,3450,0,2002,0,98010,47.3420,-122.025,3350,39750
91,5036300431,20150311T000000,1099880,5,2.75,3520,6353,2.0,0,0,...,10,3520,0,2001,0,98199,47.6506,-122.391,2520,6250
108,1853000400,20150305T000000,680000,4,2.50,3140,28037,2.0,0,0,...,10,3140,0,1991,0,98077,47.7304,-122.082,2990,35001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21568,524059330,20150130T000000,1700000,4,3.50,3830,8963,2.0,0,0,...,10,3120,710,2014,0,98004,47.5990,-122.197,2190,10777
21573,8562790760,20140520T000000,785000,4,3.50,3070,4684,2.0,0,0,...,10,2190,880,2009,0,98027,47.5316,-122.076,2290,2664
21576,9253900271,20150107T000000,3567000,5,4.50,4850,10584,2.0,1,4,...,10,3540,1310,2007,0,98008,47.5943,-122.110,3470,18270
21593,8672200110,20150317T000000,1088000,5,3.75,4170,8142,2.0,0,2,...,10,4170,0,2006,0,98056,47.5354,-122.181,3030,7980
21597,191100405,20150421T000000,1575000,4,3.25,3410,10125,2.0,0,0,...,10,3410,0,2007,0,98040,47.5653,-122.223,2290,10125

In [22]:
#How many null values are there in the dataset?
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [23]:
#OR
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  int64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(4), int64(16), object(1)
memory usage: 3.5+ MB

In [30]:
a=df[df['id']==9126100861]
a['waterfront'].count()

np.int64(1)

In [35]:
# Does this 9126100861 customer have a waterfront?
a=df[df['id']==9126100861]
#a['waterfront'].count()#count check for non null values return 1 means 0 null value
a['waterfront'].values[0]#return 0 no waterforts

np.int64(0)

In [37]:
# How many houses have 3 views?
df[df['view']==3].count()

id               510
date             510
price            510
bedrooms         510
bathrooms        510
sqft_living      510
sqft_lot         510
floors           510
waterfront       510
view             510
condition        510
grade            510
sqft_above       510
sqft_basement    510
yr_built         510
yr_renovated     510
zipcode          510
lat              510
long             510
sqft_living15    510
sqft_lot15       510
dtype: int64

In [38]:
#What is the lowest price of the house?
df['price'].min()

75000

In [41]:
#
df['sqft_living'].max()

13540

In [44]:
#How to check the duplicate values on id,grade and location?
df.duplicated(subset=['id','zipcode','grade'])

0        False
1        False
2        False
3        False
4        False
         ...
21608    False
21609    False
21610    False
21611    False
21612    False
Length: 21613, dtype: bool

In [47]:
#What will be the correlation between the columns sqft_living and sqft_above?
df['sqft_living'].corr(df['sqft_above'])

np.float64(0.876596598681318)

What value will you get on the left side after printing a series format data?  ans index